VENV_PATH="/home/hwpark/.venv"
TRACE_ROOT="/home/hwpark/workspace/storage/trace/champsim"
FEED_ROOT="/home/hwpark/workspace/storage/feed/champsim"
LOG_ROOT="/home/hwpark/workspace/storage/log/ChampSim"
SIM_BIN="/home/hwpark/workspace/simulator/ChampSim/bin/champsim"
